before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: mii-lama.bin
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X "main.buildString={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    dir: ./cmd/

archives:
  - rlcp: true
    format: tar.gz
    files:
      - README.md
      - LICENSE
      - config.sample.toml
      - prometheus.sample.yml

    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

dockers:
  - image_templates: ["ghcr.io/zerodha/mii-lama:{{ .Tag }}-amd64"]
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
    extra_files:
      - config.sample.toml

docker_manifests:
  - name_template: ghcr.io/zerodha/mii-lama:{{ .Tag }}
    image_templates:
      - ghcr.io/zerodha/mii-lama:{{ .Tag }}-amd64
      - ghcr.io/zerodha/mii-lama:{{ .Tag }}-arm64
  - name_template: ghcr.io/zerodha/mii-lama:latest
    image_templates:
      - ghcr.io/zerodha/mii-lama:{{ .Tag }}-amd64
